name: Check code quality

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - run: yarn install
      - run: yarn lint
