name: Check code quality

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and run checks
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
          cache: 'yarn'

      - run: |
          yarn install
          yarn lint
